### ISSUE TITLE
脚本的青龙2.10.13版本没有映射deps目录导致通知文件会被覆盖

### ISSUE THREAD

**Issue by DaoLuan0721** [shidahuilang/QL-#10]
![Screenshot_2022-08-03-13-52-20-74_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/52785205/182534456-a9f887b5-4e53-4145-a17d-0342074c6e8f.jpg)

**Comment by shidahuilang** [comment]
收到，因为当时写的时候还没有这个目录，我加进去
